### ISSUE TITLE
JSON.json(::Pair)

### ISSUE THREAD

**Issue by quinnj** [JuliaIO/JSON.jl#106]
Could we have the following?

``` julia
t = Pair("hey",1)
JSON.json(t)
```

results in

``` json
{\"hey\": 1}
```

or would this go against a fundamental tenet?

**Comment by kmsquire** [comment]
Sounds reasonable to me.

**Comment by alexmorley** [comment]
Don't know if this is still wanted but could be fudged with:
`JSON.json(a::Pair) = JSON.json(Dict(a))
`

**Comment by TotalVerb** [comment]
That's not a good way to fudge it. Please read the README (look up `lower`) for how you might implement this. A PR is welcome.

**Comment by TotalVerb** [comment]
Although I personally think `[a, b]` is a better equivalent for `a => b` than `{a : b}` is. Especially concerning to me is that `{a : b}` will turn something like `1 => 2` into `{"1": 2}`, because JSON only has string key types. @quinnj @kmsquire, could you explain your thoughts on why this change would be a good idea?

**Comment by alexmorley** [comment]
Sorry I meant that as a fudge for a user if they particularly want that behaviour.

**Comment by kmsquire** [comment]
@totalverb, in my experience, most (or at least many) uses of JSON are looking for interoperability with other languages, and for human readability. For this, users have to put up with its limitations, including that it only has one number type, and that it requires that all keys be strings.

For this example in particular, Pair is generally meant to be used as part of a Dict.  On the surface, when I read this suggestion, encoding it like a Dict seemed reasonable if one is looking to read that pair in another language (interoperability), and the user already has to keep in mind JSON limitations. But I'm open to arguments that this complicates the encoder and that the user should be encouraged to simply convert it to a Dict or some other data structure. 

I'll check when I get to a computer, but I forget how JSON.jl handles Dicts with integer keys. In any case, if a user does use integer keys (in a Dict or a Pair), then he/she already has to deal with that choice when working in a target language that doesn't support integer keys (like JavaScript). The user probably needs to either convert to a more suitable data structure that JSON can handle, or should consider using a different encoding method that handles integer keys better. 

Cheers!

**Comment by TotalVerb** [comment]
What I am not seeing is the use case for `x => y` to `{x : y}`, since the former is not an associative type. I would personally expect `[x, y]`.

**Comment by kmsquire** [comment]
@TotalVerb, I don't have a use case, and I see your point.  @quinnj, do you have specific use case?

**Comment by quinnj** [comment]
A `Pair` is definitely not a `[x, y]`; the entire reason we have `Pair` is as a "building block" of sorts for Dicts. i.e. it's a direct mapping of one object to another, a single key-value pair. So, IMO, it definitely makes sense to have `{x : y}` instead.

A great use-case I have for this is in `HTTP.get(url; headers="Content-Type"=>"application/json")`; if I just need to pass in a single additional header w/ a request, I don't have to create an entire `Dict`; I can instead pass in a single `Pair` and everything just works.

But really, the fact that `Pair` is meant to be a single "key-value" pair is, IMO, the biggest reason to do this.

**Comment by TotalVerb** [comment]
After some thought, that's reasonable. If there aren't any objections, we should do this.
