### ISSUE TITLE
Write empty Nullable types as null

### ISSUE THREAD

**Issue by mrow84** [JuliaIO/JSON.jl#132]
Apologies if I've misunderstood something, but it seems like Nullable values don't get written as JSON null if they are empty. Sorry for not setting up a pull request, but I think adding something like this should fix it:

    function _print{T}(io::IO, state::State, n::Nullable{T})
        if isnull(n)
            Base.print(io, "null")
        else
           _print(io, state, get(n))
        end
    end

**Comment by TotalVerb** [comment]
This should hopefully be easy to add, without adding more `_print` overloads, once #151 is finished.
