### ISSUE TITLE
Access to undefined reference serializing `#undef`

### ISSUE THREAD

**Issue by TotalVerb** [JuliaIO/JSON.jl#159]
...when serializing `Nullable{RefType}`, where `RefType` is a non-bits type.

``` julia
julia> JSON.json(Nullable{String}())
ERROR: UndefRefError: access to undefined reference
 in _print(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::JSON.State{false}, ::Nullable{String}) at /home/fengyang/.julia/v0.5/JSON/src/JSON.jl:158
 in print(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Nullable{String}, ::Int64) at /home/fengyang/.julia/v0.5/JSON/src/JSON.jl:204
 in #sprint#221(::Void, ::Function, ::Int64, ::Function, ::Nullable{String}, ::Vararg{Any,N}) at ./strings/io.jl:37
 in json(::Nullable{String}) at /home/fengyang/.julia/v0.5/JSON/src/JSON.jl:217
```

Edit: This problem is no longer relevant for `Nullable`, but it remains an issue for other types that may contain `#undef`.

**Comment by kmsquire** [comment]
I'm wondering if this is actually a problem anymore?  I get the same error if, e.g., I try to encode a `Vector{String}(undef, 10)`, but I think that's fine.

Are there other legitimate values that we want to be able to encode in JSON that contain `#undef`?

**Comment by TotalVerb** [comment]
Not that I know of at this time. When I opened the issue, it was salient for `Nullable`, but it's very likely we should just require all such types with potential #undef to define their own serialization.
