### ISSUE TITLE
JavaScript functions as values

### ISSUE THREAD

**Issue by randyzwitch** [JuliaIO/JSON.jl#170]
I know it's not part of the JSON _data format_ specification, but is there a way to pass JavaScript functions within JSON created by Julia?

So much of what I do in Julia involves generating JSON, and in some JavaScript libraries, the parser will evaluate functions (and seems that it is the JS library dev preference).

So is there a way to create something like:

```
{
    symbolSize: function (data) {
        return Math.sqrt(data[2]) / 5e2;
    }
}

```

**Comment by yuyichao** [comment]
Are you talking about a representation of J's functions? Or a transpiler

**Comment by randyzwitch** [comment]
I would just want to pass literal JS syntax as a value; were I to pass it as a String, it would be wrapped in double-quotes

**Comment by TotalVerb** [comment]
I can put this on the todo list for #169.

**Comment by randyzwitch** [comment]
@TotalVerb Do you have an idea how to do this? I've been fooling with this using `replace` on the string representation post `JSON.json(obj)`, but obviously it'd be much better to be part of the parser.

If you can give me a hint (if you know how to do it), I've got no problem trying to submit a PR. Thanks!

**Comment by TotalVerb** [comment]
@randyzwitch Let me see if I understand you. You want to go from Julia to JSON (serializing), with specific values in the resulting JSON not being quoted?

Do you need the other way too: going from JSON with some unquoted values to Julia?

**Comment by randyzwitch** [comment]
I just need to serialize, as my Julia output gets read into JavaScript. 

Some of the functionality of the JavaScript library I'm wrapping can only be accessed by passing JS functions (which is not valid JSON, but is valid in JavaScript).

So I just want to pass a string literal without quoting, I don't want to transpile a Julia function to a JavaScript function.

**Comment by TotalVerb** [comment]
This would be quite easy to do with #162, which I just opened for review. I included your use case as a [test](https://github.com/TotalVerb/JSON.jl/blob/1de4701baa03ef7b3ad4b7413954e9b77b2a4a8e/test/serializer.jl) here. I don't know if it will be useful enough to be in JSON.jl itself, but I think in the long run it may be reasonable to have this and other custom serialization patterns in a package.

**Comment by randyzwitch** [comment]
Great! I’ll pull in the PR and test it out in my application, then comment on the PR.

**Comment by randyzwitch** [comment]
I don't quite see how to use this (since it's not exported)...Since you're not planning on having this as part of the package, should I be placing the code for JS functions inside my package?

**Comment by TotalVerb** [comment]
I want to avoid having too many "niche" types in the package. Instead, it should be easy to roll your own type and have it "backed" by JSON.jl. So yes, I do suggest you to have that function and type (it isn't too many lines of code) in your package. Any interface suggestions are of course welcome.

**Comment by TotalVerb** [comment]
Addressed by #162.

**Comment by JobJob** [comment]
I'm in the same boat as Randy, just to be concrete, say I have:
```
immutable JSString
    s::String
end

JSON.lower(x::JSString) = x.s

jsfn = JSString("function (){ alert('heyyy!' }")
```

I'd like `JSON.print(STDOUT, jsfn)` to print without quotes, i.e. `function (){ alert('heyyy!' }` not `"function (){ alert('heyyy!' }"`

Is it correct to say that I just need to define: 
```
JSON.show_json(io::JSON.Writer.StructuralContext, 
    s::JSON.Serializations.CommonSerialization, 
    x::JSString) = print(io, x.s)
``` 
?

I also want to support `Dict("myfn"=>jsfn)` and prob Arrays `[jsfn1, jsfn2]` if that makes a difference.

**Comment by TotalVerb** [comment]
This might work, but CommonSerialization is intended to always return valid JSON. It is only acceptable to do this if you ensure JSString objects never leave your package, as otherwise these objects can disrupt other packages use of JSON.

A better approach in my opinion is the one used at line 44 here. You'll need to use a custom way to create the JSON, but it's straightforward to define an internal JSON function using sprint. https://github.com/JuliaIO/JSON.jl/blob/master/test/serializer.jl

**Comment by JobJob** [comment]
Great! Thanks for the very prompt and informative reply. 

This is (essentially) what I ended up going with:
```
struct JSString
    s::String
end

struct JSEvalSerialization <: JSON.Serializations.CommonSerialization end 

JSON.show_json(io::JSON.Writer.StructuralContext, ::JSEvalSerialization, x::JSString) =
    Base.print(io, x.s)
 
jsevalstr(x) = sprint(io->JSON.show_json(io, JSEvalSerialization(), x))
```
```
jsfn = JSString("function (){ alert('heyyy!') }")
jsevalstr([1,2, Dict(:handler=>jsfn)]) |> println
```
Outputs (as desired):
```
[1,2,{"handler":function (){ alert('heyyy!') }}]
```

Thanks!
