### ISSUE TITLE
Transfer to a different org - perhaps JuliaIO?

### ISSUE THREAD

**Issue by ViralBShah** [JuliaIO/JSON.jl#171]
I suggest transferring this to JuliaWeb or some other org. Thoughts?

**Comment by EricForgy** [comment]
JuliaWeb makes sense to me.

**Comment by kmsquire** [comment]
I would actually propose JuliaIO, as JSON isn't strictly for web programming.

That would also pave the way for, e.g., ProtoBuf.jl and MsgPack.jl to move there. 

It's also possible that these and some other packages (CSV.jl, Feather.jl) should be gathered together somewhere else, as JuliaIO wasn't actually targeted at these packages.

**Comment by TotalVerb** [comment]
:+1: for JuliaIO.

**Comment by ViralBShah** [comment]
JuliaIO seems does seem like a better place.

**Comment by ViralBShah** [comment]
@tkelman Do you have admin on JuliaIO?

**Comment by ViralBShah** [comment]
@tanmaykm Should we transfer ProtoBuf.jl and related packages to JuliaIO?

About CSV.jl, I believe it uses DataStreams.jl and is in JuliaDB. Perhaps JuliaIO is the right place. @quinnj Thoughts?

**Comment by tkelman** [comment]
CSV.jl is in JuliaData along with DataStreams. Yes I have admin on JuliaIO.

**Comment by ViralBShah** [comment]
Let's at least move JSON.jl to JuliaIO.

**Comment by tanmaykm** [comment]
I'm open to move ProtoBuf.jl to JuliaIO.
I was also considering JuliaInterop. But maybe that's appropriate only for higher level packages?

**Comment by tkelman** [comment]
@staticfloat can you re-enable appveyor here? looks like it's running on your account

**Comment by staticfloat** [comment]
I would, but I don't seem to have admin rights to this repo now.
