### ISSUE TITLE
The test case is somehow broken

### ISSUE THREAD

**Issue by ir193** [JuliaIO/JSON.jl#179]
I think there is some problem with the test case.
I encountered this error with julia 0.5.0 and 0.6.0-dev

> root@ae81e72b9cf3:/usr/myapp/test# julia runtests.jl 
> Test Failed
>   Expression: JSON.parse(JSON.json(fixednum)) == Float64(fixednum)
>    Evaluated: Dict{String,Any}(Pair{String,Any}("i",4044)) == 0.1234130859375
> ERROR: LoadError: LoadError: There was an error during testing
>  in record(::Base.Test.FallbackTestSet, ::Base.Test.Fail) at ./test.jl:397
>  in do_test(::Base.Test.Returned, ::Expr) at ./test.jl:281
>  in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
>  in process_options(::Base.JLOptions) at ./client.jl:262
>  in _start() at ./client.jl:318
> while loading /usr/myapp/test/lowering.jl, in expression starting on line 20
> while loading /usr/myapp/test/runtests.jl, in expression starting on line 307
> 

If I understand this right, after convert fixednum into string, it is a dictionary. I am not sure right now,  should json and parse method treat fixed number as special case or just modify the test case?

**Comment by TotalVerb** [comment]
Something is wrong here. I will investigate.

**Comment by TotalVerb** [comment]
@ir193 To diagnose this problem we will need some more information. What type is `fixednum`? What package provides this type?

My understanding is that `fixednum` is a composite type with a single `i` field, and for some reason it is not subtyping `Real` properly.

**Comment by ir193** [comment]
@TotalVerb Error is on the last line of [https://github.com/JuliaIO/JSON.jl/blob/master/test/lowering.jl](url). 
typeof(fixednum) is FixedPointNumbers provided by [https://github.com/JuliaMath/FixedPointNumbers.jl](url)

**Comment by TotalVerb** [comment]
Thanks for the quick reply. This test is passing locally, so I'd like some more information if possible.

Can you run `Pkg.status("JSON")`?

**Comment by ir193** [comment]
```
julia> Pkg.status("JSON")
 - JSON                          0.8.0

```

```
julia> JSON.lower(Fixed16(1.234))
JSON.AssociativeWrapper{FixedPointNumbers.Fixed{Int32,16}} with 1 entryError showing value of type JSON.AssociativeWrapper{FixedPointNumbers.Fixed{Int32,16}}:
ERROR: MethodError: no method matching start(::JSON.AssociativeWrapper{FixedPointNumbers.Fixed{Int32,16}})
Closest candidates are:
  start(::SimpleVector) at essentials.jl:188
  start(::Base.MethodList) at reflection.jl:409
  start(::IntSet) at intset.jl:184
  ...
 in show(::IOContext{Base.Terminals.TTYTerminal}, ::MIME{Symbol("text/plain")}, ::JSON.AssociativeWrapper{FixedPointNumbers.Fixed{Int32,16}}) at ./replutil.jl:46
 in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::MIME{Symbol("text/plain")}, ::JSON.AssociativeWrapper{FixedPointNumbers.Fixed{Int32,16}}) at ./REPL.jl:134
 in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::JSON.AssociativeWrapper{FixedPointNumbers.Fixed{Int32,16}}) at ./REPL.jl:137
 in display(::JSON.AssociativeWrapper{FixedPointNumbers.Fixed{Int32,16}}) at ./multimedia.jl:184
 in print_response(::Base.Terminals.TTYTerminal, ::Any, ::Void, ::Bool, ::Bool, ::Void) at ./REPL.jl:156
 in print_response(::Base.REPL.LineEditREPL, ::Any, ::Void, ::Bool, ::Bool) at ./REPL.jl:141
 in (::Base.REPL.##22#23{Bool,Base.REPL.##33#42{Base.REPL.LineEditREPL,Base.REPL.REPLHistoryProvider},Base.REPL.LineEditREPL,Base.LineEdit.Prompt})(::Base.LineEdit.MIState, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Bool) at ./REPL.jl:654
 in run_repl(::Base.REPL.LineEditREPL, ::Base.##967#968) at ./REPL.jl:190


```


Am I not using the latest version? Sorry if I did that.

**Comment by TotalVerb** [comment]
This is indeed the latest version, yet I still am not able to reproduce the problem. Can you check `Pkg.status("FixedPointNumbes")` also?

**Comment by ir193** [comment]
```
julia> Pkg.status("FixedPointNumbers")
 - FixedPointNumbers             0.2.1

```

And same result on julia-nightlies of fedora (0.6.0-dev) and julia docker image

**Comment by TotalVerb** [comment]
I can confirm that I have reproduced this once, but for some reason I cannot reproduce it again, even executing the same sequence of commands. It's possible this is a Julia bug.

**Comment by ir193** [comment]
Did I run this tests in a wrong way? I download julia from docker hub, I git clone this repo for the test cases, and install JSON.jl DataStructures.jl via julia repl. Is that currect way to do that ?

**Comment by TotalVerb** [comment]
The usual way is to run, from the Julia REPL,

```julia
julia> Pkg.add("JSON")
julia> Pkg.test("JSON")
```

**Comment by ir193** [comment]
I think the latest version of JSON.jl in METADATA is  https://github.com/JuliaIO/JSON.jl/commit/0e3647317c75f1e35b54a407bc6f9501ca765006.
But the new test case about fixednumber is introduced in  https://github.com/JuliaIO/JSON.jl/commit/6b08c8dc4d70a26265b573130bc9982feeef5d94

**Comment by TotalVerb** [comment]
That's indeed a good point, but I should be on a master branch myself. Try

```julia
julia> Pkg.checkout("JSON")
julia> Pkg.test("JSON")
```

**Comment by ir193** [comment]
All tests pass. Even I directly run julia runtests.jl
I think my mistake is testing old version with newer test case.
Really sorry for disturbing

**Comment by TotalVerb** [comment]
OK, no problem, thanks for the report!
