### ISSUE TITLE
ERROR: type String has no field data

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaIO/JSON.jl#183]
At [cfac61d](https://github.com/JuliaLang/julia/commit/cfac61d88625e3d58b9f0dbd4d9959e640b2a9f0) of julia master branch due to [faster `String` allocation #19449](https://github.com/JuliaLang/julia/pull/19449).

Requires changes in JSON.jl, Parser.jl and specialized.jl .

**Comment by stevengj** [comment]
Already fixed in #180.

**Comment by josefsachsconning** [comment]
Could it be tagged, then?

**Comment by TotalVerb** [comment]
Is attobot turned on for this repository? @tkelman

**Comment by Keno** [comment]
It is. See https://github.com/JuliaLang/METADATA.jl/pull/7563. Did you try to tag it and it didn't work?

**Comment by TotalVerb** [comment]
The tag has been merged, so I'm closing this issue.

@Keno, thanks. No, I hadn't tried.
