### ISSUE TITLE
Serialization of Set should (probably) not dump the current dictionary representation

### ISSUE THREAD

**Issue by oyd11** [JuliaIO/JSON.jl#196]
This may have to be changed in the Set implementation instead, current behaviour : 
`julia> VERSION`
`v"0.5.1"`
`julia> json( Set([1,2]) )`
`"{\"dict\":{\"2\":null,\"1\":null}}"`

probably desired behaviour:
`julia> json( collect(Set([1,2])) )`
` "[2,1]" `
or define:
`JSON.lower(s::Set) = collect(s)`
since Set is a basic type, this might break some code (I doubt anyone counts on this behaviour)

**Comment by TotalVerb** [comment]
This makes sense. You're right, the change should be safe because the current serialization is silly.

**Comment by oyd11** [comment]
yes,  #206 closes this as well once it's integrate to master
