### ISSUE TITLE
Implement DataStream Interface

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaIO/JSON.jl#198]
That seems to be a really nice interface for allowing you to write to all sorts of formats. JSON seems left out. Is this possible?

**Comment by TotalVerb** [comment]
See https://github.com/joshbode/JSONStreams.jl. It's definitely possible with the existing functionality, but much of it needs to be documented still.

**Comment by TotalVerb** [comment]
Closing in favor of JSONStreams.jl.
