### ISSUE TITLE
WARNINGS with Julia 0.7

### ISSUE THREAD

**Issue by femtotrader** [JuliaIO/JSON.jl#211]
Hello,

Similar to https://github.com/JuliaWeb/URIParser.jl/issues/51

when running CI for one of my packages, it shows

```
WARNING: deprecated syntax "type" at /home/travis/.julia/v0.7/JSON/src/Parser.jl:21.
Use "mutable struct" instead.
WARNING: deprecated syntax "type" at /home/travis/.julia/v0.7/JSON/src/Parser.jl:26.
Use "mutable struct" instead.
WARNING: deprecated syntax "immutable" at /home/travis/.julia/v0.7/JSON/src/Serializations.jl:38.
Use "struct" instead.
WARNING: deprecated syntax "immutable" at /home/travis/.julia/v0.7/JSON/src/Writer.jl:14.
Use "struct" instead.
WARNING: deprecated syntax "type" at /home/travis/.julia/v0.7/JSON/src/Writer.jl:84.
Use "mutable struct" instead.
WARNING: deprecated syntax "type" at /home/travis/.julia/v0.7/JSON/src/Writer.jl:97.
Use "mutable struct" instead.
WARNING: deprecated syntax "immutable" at /home/travis/.julia/v0.7/JSON/src/Writer.jl:108.
Use "struct" instead.
WARNING: PkgDev.jl is not configured. Please, run `PkgDev.config()` before performing any operations.
```

That's just a warning...

Kind regards

**Comment by KristofferC** [comment]
While not being author of this package I would suggest not going around filing issues for deprecation warnings on 0.7. It is a moving target and not really something that should be used for real work. PRs to fix these warnings are usually quite simple.

**Comment by stevengj** [comment]
We can't fix these particular warnings without dropping/branching 0.5 support, which I don't think we should do until the end of summer or so.

**Comment by TotalVerb** [comment]
These warnings should be fixed on master. We just need to tag a release.

**Comment by TotalVerb** [comment]
Tagged: https://github.com/JuliaIO/JSON.jl/releases/tag/v0.13.0

If the issue persists, please reopen.

**Comment by TotalVerb** [comment]
By the way -- while @KristofferC's comment is correct in general, please do continue to report any warnings, etc. for JSON. Packages such as JSON and Compat are more depended on around the ecosystem and should go through extra effort to remain deprecation free, even in a moving target.

**Comment by TotalVerb** [comment]
Of course, there are still warnings with 0.7. PR incoming.

**Comment by TotalVerb** [comment]
Never mind, those warnings are from DataStructures and are test-only. There don't seem to be any JSON warnings.
