### ISSUE TITLE
Marshalling and Unmarshalling JSON to/from Julia types

### ISSUE THREAD

**Issue by jebej** [JuliaIO/JSON.jl#214]
This is related to #96, but I think it deserves its own issue.

It would be nice to have the same type of parsing as go, where it is possible to "marshal" and "unmarshal" a JSON object into a struct. This page explains it pretty well: https://eager.io/blog/go-and-json/.

It seems that the marhsalling part already works by defining custom `lower` methods. Having a function `JSON.parse(jsonstring,MyStruct)` would allow julia structs to be jsonified and round tripped back to julia without any information loss.

**Comment by TotalVerb** [comment]
Have you seen the [Unmarshal.jl](https://github.com/lwabeke/Unmarshal.jl) package?

I do agree that it is nice to have symmetry from defining `lower` and its inverse at the same time, but we have to be a little careful in a more dynamic language like Julia. Unmarshal does a good job of this, but there is certainly room to improve it.

**Comment by jebej** [comment]
I hadn't seen it, thanks. I suppose it would be nice to have it better integrated in JSON to void using an intermediate `Dict`.

**Comment by jebej** [comment]
It seems this feature is now provided by [JSON2.jl](https://github.com/quinnj/JSON2.jl)

**Comment by samoconnor** [comment]
See also https://discourse.julialang.org/t/announce-a-different-way-to-read-json-data-lazyjson-jl/9046/2?u=samoconnor

**Comment by TotalVerb** [comment]
It looks like this is not actionable at the moment, and the functionality is provided by JSON2.
