### ISSUE TITLE
Large unsigned integer returns nonsensical result

### ISSUE THREAD

**Issue by Wikunia** [JuliaIO/JSON.jl#223]
Is it possible to define the type of the dict in the parsing command.
My json looks like 
`{"201736327611975630":18005722827070440994}` which seems to be handled as String and then kind of integer but it's actually unsigned. Therefore after parsing I get results ending in something like `-441021246639110622`

**Comment by kmsquire** [comment]
You can actually pass the dictionary type (including the type parameters) to `JSON.parse`.  However, for your example, this still doesn't quite work right:

```julia
julia> JSON.parse("""{"201736327611975630":18005722827070440994}""", dicttype=Dict{String, Int128})
Dict{String,Int128} with 1 entry:
  "201736327611975630" => -441021246639110622

julia> JSON.parse("""{"201736327611975630":18005722827070440994}""", dicttype=Dict{String, UInt128})
ERROR: InexactError()
 in setindex!(::Dict{String,UInt128}, ::Int64, ::String) at ./dict.jl:643
 in parse_object(::JSON.Parser.MemoryParserState, ::Type{T}) at /Users/kevin/.julia/v0.5/JSON/src/Parser.jl:219
 in parse_value(::JSON.Parser.MemoryParserState, ::Type{T}) at /Users/kevin/.julia/v0.5/JSON/src/Parser.jl:160
 in #parse#1(::Type{Dict{String,UInt128}}, ::Function, ::String) at /Users/kevin/.julia/v0.5/JSON/src/Parser.jl:377
 in (::JSON.Parser.#kw##parse)(::Array{Any,1}, ::JSON.Parser.#parse, ::String) at ./<missing>:0
```

Note that your large unsigned number isn't considered portable.  Quoting from the [JSON spec](https://tools.ietf.org/html/rfc7159#section-6):

```
   This specification allows implementations to set limits on the range
   and precision of numbers accepted.  Since software that implements
   IEEE 754-2008 binary64 (double precision) numbers [IEEE754] is
   generally available and widely used, good interoperability can be
   achieved by implementations that expect no more precision or range
   than these provide....

   ...numbers that are integers and
   are in the range [-(2**53)+1, (2**53)-1] are interoperable in the
   sense that implementations will agree exactly on their numeric
   values.
```

The Julia implementation will actually parse integers as `Int64`, so the numerical range is implicitly `[-(2^63-1), (2^63)-1)]` (and should probably be documented as such).  But this still isn't big enough to parse your integer.  (Relevant code is [here](https://github.com/JuliaIO/JSON.jl/blob/master/src/Parser.jl#L316-L323).)

@TotalVerb, do you have any thoughts on actually parsing a number that would fit into an `Int128`?  It's certainly doable, but I'm wondering how easy it is without compromising parsing speed for most other integers.

**Comment by TotalVerb** [comment]
We can probably just return a `Float64` in such cases. Thus we lose precision (as is allowed) but we do not return a wrong answer like `-183820312242442`.

**Comment by kmsquire** [comment]
See #224 for a solution to the original problem.  Although, the given solution does not actually check for overflow.  Maybe I should add that...

**Comment by kmsquire** [comment]
... and there doesn't seem to be a nice way without explicitly checking for overflow at each iteration.   I can check for a negative value before the `ifelse` [here](https://github.com/JuliaIO/JSON.jl/blob/master/src/Parser.jl#L316-L323), but a large enough number will be positive by that point.

An easy solution would be to parse using https://github.com/JeffreySarnoff/SaferIntegers.jl.  Using #224:

```julia
julia> JSON.parse("""18005722827070440994999999""", inttype=Int64)
3510675137339035327

julia> JSON.parse("""18005722827070440994999999""", inttype=SafeInt64)
ERROR: OverflowError()
Stacktrace:
 [1] checked_mul at ./checked.jl:287 [inlined]
...
```

**Comment by TotalVerb** [comment]
Overflow checking can probably be implemented in a separate change. Note that `checked_mul` and `checked_add` are from `Base`. I think SaferIntegers.jl just exposes them in a nicer interface, but it would not be necessary to add that dependency.
