### ISSUE TITLE
Warning: `IOBuffer(maxsize::Integer)` is deprecated

### ISSUE THREAD

**Issue by samoconnor** [JuliaIO/JSON.jl#241]
There has been a performance regression in the last few days.
A test that was taking ~1s is now taking ~6s and I'm seeing:
See the performance test output here: https://github.com/samoconnor/LazyJSON.jl#benchmarks 

```
┌ Warning: `IOBuffer(maxsize::Integer)` is deprecated, use `IOBuffer(read=true, write=true, maxsize=maxsize)` instead.
│   caller = parse_string(::JSON.Parser.MemoryParserState) at specialized.jl:17
└ @ JSON.Parser specialized.jl:17
```

Julia: 0.7.0-DEV.3761

JSON.jl: 98727675b635c8428effa30a2287a9fe6370e664

**Comment by stevengj** [comment]
Deprecations slow things down a lot.   (`maxsize` is now a keyword.)

Anyway, did you mean to file an issue at LasyJSON.jl?

**Comment by samoconnor** [comment]
> Anyway, did you mean to file an issue at LasyJSON.jl?

No, I referred to the LasyJSON.jl benchmarks because they compare performance between JSON.jl and LazyJSON.jl. JSON.jl slowed down by a factor of 6 since this deprecation.
 
I guess because of this:
https://github.com/JuliaIO/JSON.jl/blob/18892256c12e943a19aee303043853f25defaec9/src/specialized.jl#L17
