### ISSUE TITLE
Reading strings containing newlines

### ISSUE THREAD

**Issue by jebej** [JuliaIO/JSON.jl#258]
Is is possible to read string containing newlines? Right now, the parser throws "ASCII control character in string"

**Comment by TotalVerb** [comment]
This is not allowed by the JSON spec. Newlines must be escaped as `\n`.

**Comment by jebej** [comment]
What does that mean? That the string must contain `\\n`?

**Comment by kmsquire** [comment]
I wonder if we might provide an option to allow parsing of "out of spec" json. Of course, that would require a bit of work on the parser (or an alternative parser), which isn't trivial.

**Comment by samoconnor** [comment]
Where is the out of spec JSON coming from?
It might be best to build a pre-procsssor to fix the broken JSON + try to get the source to fix it in the  future.
Proliferation of allowing-slightly-out-of-spec-data is the bane of interoperability (and parser writers).
