### ISSUE TITLE
Can't serialize type Ptr{Nothing}

### ISSUE THREAD

**Issue by TheOnlyArtz** [JuliaIO/JSON.jl#259]
This is my code:
```julia
import WebSockets
using OpenTrick

io = opentrick(WebSockets.open, "wss://gateway.discord.gg/?v=6&encoding=json")
json = JSON.print(io)

### {"io":{"socket":{"data":ERROR: Cannot serialize type Ptr{Nothing}
```
EDIT: This is what the response looks like:
![image](https://user-images.githubusercontent.com/30025874/46156523-59a01300-c282-11e8-9c77-02bbc7f824fa.png)

**Comment by TheOnlyArtz** [comment]
I manage to get the byte array by calling
```julia
byteArray = read(io)
```

**Comment by KristofferC** [comment]
The content of that byte array is already in JSON format though?

```
julia> b = read(io);

julia> s = String(b)
"{\"t\":null,\"s\":null,\"op\":10,\"d\":{\"heartbeat_interval\":41250,\"_trace\":[\"gateway-prd-main-8v6p\"]}}"

julia> JSON.parse(s)
Dict{String,Any} with 4 entries:
  "t"  => nothing
  "op" => 10
  "s"  => nothing
  "d"  => Dict{String,Any}("heartbeat_interval"=>41250,"_trace"=>Any["gateway-prd-main-8v6p"])
```

**Comment by TheOnlyArtz** [comment]
> The content of that byte array is already in JSON format though?
> 
> ```
> julia> b = read(io);
> 
> julia> s = String(b)
> "{\"t\":null,\"s\":null,\"op\":10,\"d\":{\"heartbeat_interval\":41250,\"_trace\":[\"gateway-prd-main-8v6p\"]}}"
> 
> julia> JSON.parse(s)
> Dict{String,Any} with 4 entries:
>   "t"  => nothing
>   "op" => 10
>   "s"  => nothing
>   "d"  => Dict{String,Any}("heartbeat_interval"=>41250,"_trace"=>Any["gateway-prd-main-8v6p"])
> ```

Thank you very much it worked!
