### ISSUE TITLE
Update Julia version badge to 1.X

### ISSUE THREAD

**Issue by houd1ni** [JuliaIO/JSON.jl#271]
Connected to old #251

I've successfully tested it on a large database on Julia 1.0.2.

Maybe, update REQUIRE and the badge of README.md ?

**Comment by TotalVerb** [comment]
I'm not sure there are 1.0 badges yet.

**Comment by houd1ni** [comment]
@TotalVerb  Hi! Yeah, I see. Left the issue there: https://github.com/JuliaLang/METADATA.jl/issues/19868

I hope, they will collaborate on this, because it lefts real stable and the first prod-ready compatible version on the street.
