### ISSUE TITLE
Use more specific type for arrays of objects

### ISSUE THREAD

**Issue by leo60228** [JuliaIO/JSON.jl#278]
Currently, `typeof(JSON.parse("""{"arr": [{"a": "b"}, {"c": "d"}]}""")["arr"])` is `Any[]`, despite `typeof(JSON.parse("""{"arr": [{"a": "b"}, {"c": "d"}]}""")["arr"][1])` and `typeof(JSON.parse("""{"arr": [{"a": "b"}, {"c": "d"}]}""")["arr"][2])` both being `Dict{String, Any}`.

**Comment by TotalVerb** [comment]
duplicate of #139
