### ISSUE TITLE
Tag a 1.0.0

### ISSUE THREAD

**Issue by davidanthoff** [JuliaIO/JSON.jl#283]
Could we tag a version 1.0.0?

That would make it much easier for packages that depend on this one here to use semver compat bounds in Project.toml. The problem is that pre 1.0.0, every minor update is considered breaking, whereas starting with 1.0.0 one can use the full semver semantics, which make everything easier.

Also, it seems that this package is so widely used with the current API, that one might as well declare what we have as stable and done, right?

**Comment by TotalVerb** [comment]
I think this is reasonable. Let's get all the current outstanding PRs dealt with first, and then tag a first major version.
