### ISSUE TITLE
Tag 0.20.1 is lower than 0.21.0

### ISSUE THREAD

**Issue by jonathonf** [JuliaIO/JSON.jl#304]
The last tag is 0.20.1 which is lower than the previous tag 0.21.0.

Was this intentional?

**Comment by davidanthoff** [comment]
Yes, 0.20.1 was a patch release on the 0.20.x line that was tagged on a branch off 0.20.0.

**Comment by yiyuezhuo** [comment]
But  `add JSON@0.20.1` will decrease `Plots` version from `v1.6.3` to `v0.27.1` (no `[compat]` version)... Is it possible to release a `0.21.1` to contain fix in `0.20.1` such as https://github.com/JuliaIO/JSON.jl/pull/293 ?

**Comment by KristofferC** [comment]
cc @kmsquire, @stevengj, @TotalVerb for help with backporting things to 0.21 (ref https://github.com/JuliaIO/JSON.jl/pull/287).
