### ISSUE TITLE
When is JSON.jl going to get to 1.0 ? 

### ISSUE THREAD

**Issue by clarkevans** [JuliaIO/JSON.jl#322]
Registrator is now complaining if you don't really pin down packages.

> The following dependencies do not have a [compat] entry that is upper-bounded and only includes a finite number of breaking releases: JSON

Hence, I now have `JSON = "0.21"` in my `[compat]` which will likely cause a release cascade when JSON bumps to v0.22.

**Comment by fredrikekre** [comment]
It would cause a similar release cascade if JSON released 2.0 though, so not sure what you mean.

**Comment by clarkevans** [comment]
@fredrikekre This is not just a technical request: it's a process request -- that JSON become stable enough to where future breaking changes are not expected.

**Comment by fredrikekre** [comment]
Isn't it already?

**Comment by clarkevans** [comment]
It's clear we have a fundamental disagreement, and it's your project.  Thank you for your consideration.

**Comment by fredrikekre** [comment]
> and it's your project.

Not at all, I don't think I have even contributed to this package.
